// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Doctors = sequelize.define('doctors', {
    // isActive: {
    //   type: DataTypes.BOOLEAN,
    // },
    // doctorType: {
    //   type: DataTypes.STRING,
    // },
    // createdAt: {
    //   type: DataTypes.DATEONLY,
    // },
    // email: {
    //   type: DataTypes.STRING,
    // },
    firstName: {
      type: DataTypes.STRING,
      field: 'firstName',
    },
    // lastName: {
    //   type: DataTypes.STRING,
    //   field: 'lastName',
    // },
  }, {
    tableName: 'Doctors',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Doctors.associate = (models) => {
    Doctors.hasMany(models.prescriptions, {
      foreignKey: {
        name: 'doctorsIdKey',
        field: 'doctorsId',
      },
      as: 'doctorsPrescriptions',
    });
  };

  return Doctors;
};
