// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Location = sequelize.define('location', {
    name: {
      type: DataTypes.STRING,
      field: 'Name',
    },
    adresse: {
      type: DataTypes.STRING,
    },
    latitude: {
      type: DataTypes.DOUBLE,
    },
    longitudes: {
      type: DataTypes.DOUBLE,
      field: 'longitudes ',
    },
  }, {
    tableName: 'location',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Location.associate = (models) => {
    Location.hasMany(models.services, {
      foreignKey: {
        name: 'locationIdKey',
        field: 'locationId',
      },
      as: 'services',
    });
  };

  return Location;
};
